Multiprocess bug
juaml/julearn pull request #110
Opened 2021-01-11 20:15 UTC by samihamdan

2021-01-12 09:11 UTC, fraimondo requested changes

2021-01-12 09:11 UTC, fraimondo commented on docs/changes/latest.inc
> +- Fix compatibility with multiprocessing in sklearn (by `Sami Hamdan`_)
let's use scikit-learn and not sklearn.

2021-01-12 09:11 UTC, fraimondo commented on julearn/scoring.py
> +        except AttributeError:
I personally do not agree to use exceptions to handle code flow. The correct way here will be to use `hasattr(estimator, 'transform_target')`

2021-01-12 09:11 UTC, fraimondo commented
Just asked for two minor changes. But despite that, good work!

2021-01-12 12:56 UTC, samihamdan commented
thx, changes should be implemented now.

2021-01-13 14:57 UTC, fraimondo approved these changes

2021-01-13 14:57 UTC, merged