Create model api
juaml/julearn pull request #115
Opened 2021-01-19 12:33 UTC by samihamdan

One way to implement #114

2021-01-20 09:43 UTC, fraimondo requested changes

2021-01-20 09:43 UTC, fraimondo commented on julearn/api.py
> +):
Missing docstring

2021-01-21 20:04 UTC, samihamdan commented
Added functionality to set model/pipeline params. 
No custom checks on it, because it will throw the proper error anyways if someone tries to set smth wrong

2021-05-06 11:49 UTC, fraimondo requested changes

2021-05-06 11:49 UTC, fraimondo commented on julearn/api.py
> +        If not None it has to be a dictionary of paramaeter value pair.
typo

2021-05-06 11:49 UTC, fraimondo commented on julearn/api.py
> +    if model_params is not None:
`prepare_model_params`

2021-05-06 12:54 UTC, fraimondo requested changes

2021-05-06 12:54 UTC, fraimondo commented on docs/changes/latest.inc
> +  - Add user facing `create_pipeline` function (by `Sami Hamdan`_)
Extra space, missing newline

2021-05-06 12:57 UTC, fraimondo approved these changes

2021-05-06 13:05 UTC, merged